# Generated by Django 5.2.17 on 2026-09-04 13:44

import django.db.models.deletion
import jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.UUIDField(help_text='client_id del cliente nell’anagrafica del Portale FBO.')),
                ('api_key', models.CharField(default=jobs.models._generate_api_key, editable=False, max_length=64, unique=True)),
                ('attivo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Destinazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.UUIDField()),
                ('piattaforma', models.CharField(choices=[('facebook', 'Facebook')], default='facebook', max_length=32)),
                ('page_id', models.CharField(max_length=255)),
                ('access_token_cifrato', models.BinaryField(help_text='Access token cifrato con Fernet (MASTER_ENCRYPTION_KEY). Non leggere/scrivere direttamente: usare access_token.')),
                ('nome_descrittivo', models.CharField(help_text='Es. "Pagina FB ASD Calcio Olgiate".', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.UUIDField()),
                ('nome', models.CharField(max_length=255)),
                ('html_content', models.TextField(help_text='Markup con placeholder tipo {{risultato}}.')),
                ('css_content', models.TextField(blank=True, null=True)),
                ('campi_richiesti', models.JSONField(default=list, help_text='Elenco dei placeholder attesi nei dati del Job, es. ["avversario", "risultato", "data"].')),
                ('attivo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.UUIDField()),
                ('dati', models.JSONField(default=dict, help_text='Valori per i placeholder del Template.')),
                ('stato', models.CharField(choices=[('in_coda', 'In coda'), ('generato', 'Generato'), ('pubblicato', 'Pubblicato'), ('errore', 'Errore')], default='in_coda', max_length=16)),
                ('immagine_path', models.CharField(blank=True, max_length=500, null=True)),
                ('post_id_risultante', models.CharField(blank=True, max_length=255, null=True)),
                ('errore_messaggio', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destinazione', models.ForeignKey(blank=True, help_text='Nullo se il job è solo generazione, senza pubblicazione.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_set', to='jobs.destinazione')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_set', to='jobs.template')),
            ],
        ),
    ]
