# Generated by Django 5.2.17 on 2026-09-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='caption',
            field=models.TextField(blank=True, help_text='Didascalia da usare in pubblicazione (POST /pubblica). Non usata se destinazione è nullo.', null=True),
        ),
    ]
