# Generated by Django 5.2.17 on 2026-09-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='altezza',
            field=models.PositiveIntegerField(default=630, help_text='Altezza dello screenshot in pixel (solo il viewport iniziale: se il contenuto è più alto, lo screenshot lo segue comunque per intero).'),
        ),
        migrations.AddField(
            model_name='template',
            name='larghezza',
            field=models.PositiveIntegerField(default=1200, help_text='Larghezza dello screenshot in pixel. Default 1200x630 (formato Facebook link/foto).'),
        ),
    ]
