# Generated by Django 5.2.17 on 2026-09-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_template_altezza_template_larghezza'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinazione',
            name='automatica_giorni',
            field=models.JSONField(blank=True, default=list, help_text='Giorni della settimana in cui è valida la pubblicazione automatica (0=lunedì...6=domenica). Vuoto = tutti i giorni.'),
        ),
        migrations.AddField(
            model_name='destinazione',
            name='automatica_ora_fine',
            field=models.TimeField(blank=True, help_text='Fine della finestra oraria per la pubblicazione automatica. Vuoto = nessun limite finale.', null=True),
        ),
        migrations.AddField(
            model_name='destinazione',
            name='automatica_ora_inizio',
            field=models.TimeField(blank=True, help_text='Inizio della finestra oraria per la pubblicazione automatica. Vuoto = nessun limite iniziale.', null=True),
        ),
        migrations.AddField(
            model_name='destinazione',
            name='pubblicazione_automatica',
            field=models.BooleanField(default=False, help_text='Se attivo, i Job con consenso pubblicano da soli (dentro la finestra sotto), senza intervento manuale.'),
        ),
        migrations.AddField(
            model_name='job',
            name='consenso_pubblicazione',
            field=models.BooleanField(default=False, help_text='Consenso a pubblicare dato dal chiamante (es. il direttore sportivo via Squadfy). Necessario ma non sufficiente per la pubblicazione automatica: serve anche che la Destinazione abbia pubblicazione_automatica attiva e si sia dentro la sua finestra giorni/orario — altrimenti il Job resta pronto per la pubblicazione manuale.'),
        ),
    ]
